name: Build & Test PR

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:  # Allow manual triggering

env:
    PROJECT_NAME: ModernBlazor.Typeahead
    NETCORE_VERSION: '9.0.x'

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Setting up .NET Core SDK ${{ env.NETCORE_VERSION }}...
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.NETCORE_VERSION }}

    - name: Restoring packages...
      run: dotnet restore

    - name: Building project...
      run: dotnet build --configuration Release --no-restore src/$PROJECT_NAME/$PROJECT_NAME.csproj

    - name: Testing...
      run: dotnet test --no-restore --verbosity normal